# Generated by Django 6.0 on 2025-12-11 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_product_price_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='token',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='token',
        ),
    ]
