# Generated by Django 6.0 on 2025-12-11 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_remove_client_token_remove_seller_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photos',
            field=models.JSONField(blank=True, default=list, help_text='Список URL фотографий (используйте загрузку файлов через админку)', verbose_name='Фотографии (устаревшее)'),
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='products/photos/', verbose_name='Фотография')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения фотографии (0 - первая)', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_photos', to='marketplace.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Фотография продукта',
                'verbose_name_plural': 'Фотографии продуктов',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['product', 'order'], name='marketplace_product_034560_idx')],
            },
        ),
    ]
